language: go
go:
  - tip
env:
  global:
    - TARGET_ARCH=amd64
    - CGO_ENABLED=1
  matrix:
    - TARGET_OS=linux
    - TARGET_OS=windows EXT=.exe CC=x86_64-w64-mingw32-gcc
before_deploy:
  - [ -n "$EXT" ] && sudo apt-get install -y binutils-mingw-w64-x86-64 gcc-mingw-w64-x86-64
  - export GOARCH=$TARGET_ARCH GOOS=$TARGET_OS
deploy:
  provider: script
  script: $HOME/gopath/src/github.com/Lafeng/deblocus/static/deploy.sh
  on:
    branch: dev
