language: go
go:
  - tip
env:
  global:
    - TARGET_ARCH=amd64
    - CGO_ENABLED=1
  matrix:
    - TARGET_OS=linux
before_deploy:
  - export GOARCH=$TARGET_ARCH GOOS=$TARGET_OS
deploy:
  provider: script
  script: $HOME/gopath/src/github.com/Lafeng/deblocus/static/deploy.sh
  on:
    branch: dev
